### ISSUE TITLE
doesn't work on mac os x?

### ISSUE THREAD

**Issue by bubenkoff** [gbb/par_psql#2] opened 2016-03-02 18:09 UTC
Is it actually supposed to work on mac?

**Comment by gbb** [comment] 2016-03-02 19:08
Can you describe the problem?
- what happens when you try to run it
- do you have postgres installed?
- Where is psql!
- does the file have execute permission set
- what version of macos and postgres are you using?

I'm on holiday but if you provide this information I'll check it out when
I'm back

**Comment by bubenkoff** [comment] 2016-03-02 19:11
there's no output at all, even if i run it with DEBUG=1
psql is there and it does run it, because when connection settings are wrong it complains about it

**Comment by bubenkoff** [comment] 2016-03-02 19:12
macosx is the latest, postgres is psql (PostgreSQL) 9.5.1

**Comment by gbb** [comment] 2016-03-02 21:57
Also yes, it should certainly work on a Mac.

**Comment by gbb** [comment] 2016-03-02 22:04
Have you read the FAQ about the type of functions that can't be
parallelized with this program?

The program generates temporary files which are run individually. If your &
marks are placed wrongly, it could cause the generated temporary files to
fail and crash. You could look at the temporary files to see what is being
run in each thread.

Until I'm back from holiday that's all I can suggest, I think. Back in a
few days!

**Comment by gbb** [comment] 2016-03-02 22:04
Also

Can you send me the script you're executing, or at least the first part?
You can mask out any passwords or sensitive information.

macosx is the latest, postgres is psql (PostgreSQL) 9.5.1

**Comment by bubenkoff** [comment] 2016-03-02 22:37
``` bash
echo 'select 1; --&' > select.sql; par_psql postgres --file=select.sql -a
```

**Comment by gbb** [comment] 2016-03-02 22:49
That's interesting, why did you put two --& in the same line? Anything
after -- is ignored by psql. This SQL doesn't make sense.

You may not put anything after the --& and it must appear at the end. That
may be what's breaking parpsql.

The parser is quite simple.

Try this script below - type it by hand, don't use echo. I think part of
the problem is you're writing some really peculiar SQL there.

Also, what happens when you run some of the examples in the documentation?

-------cut here-------

Select 1;    --&
Select 2;    --&
Select 3;    --&

**Comment by bubenkoff** [comment] 2016-03-02 22:51
that was a typo - fixed it
but the point is - i don't see any output from that, even if i skip --&
completely

On 2 March 2016 at 23:50, Graeme B Bell notifications@github.com wrote:

> That's interesting, why did you put two --& in the same line? Anything
> after -- is ignored by psql. This SQL doesn't make sense.
> 
> You may not put anything after the --& and it must appear at the end. That
> may be what's breaking parpsql.
> 
> The parser is quite simple.
> 
> Try this script below - type it by hand, don't use echo. I think part of
> the problem is you're writing some really peculiar SQL there.
> 
> Also, what happens when you run some of the examples in the documentation?
> 
> -------cut here-------
> 
> Select 1; --&
> Select 2; --&
> Select 3; --&
> On 2 Mar 2016 11:37 pm, "Anatoly Bubenkov" notifications@github.com
> wrote:
> 
> > echo 'select 1; --&; --&' > select.sql; par_psql postgres
> > --file=select.sql -a
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/gbb/par_psql/issues/2#issuecomment-191471676.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gbb/par_psql/issues/2#issuecomment-191478404.

## 

Anatoly Bubenkov

**Comment by gbb** [comment] 2016-03-02 22:55
1. Can you tell me what happens when you run the code I sent in my last
   email. Does it work? What is the output?
2. Can you try the other examples in the documentation? Do they run?
3. Can you send me exactly the code you are running.

Unfortunately I will need all 3 answers, or I won't be able to diagnose the
problem any more.

**Comment by bubenkoff** [comment] 2016-03-02 23:14
``` bash
echo 'select 1' > select.sql; par_psql postgres --file=select.sql -a
```

this code returns nothing
note that it even doesn't have any --& and it already doesn't work

**Comment by gbb** [comment] 2016-03-02 23:15
Select 1

Is not valid SQL.

**Comment by bubenkoff** [comment] 2016-03-02 23:16
how come?

try running with native psql

```
echo 'select 1' > select.sql; psql postgres --file=select.sql -a
```

**Comment by gbb** [comment] 2016-03-02 23:25
SQL commands must be terminated with a semicolon.

Try

Select 1;

**Comment by bubenkoff** [comment] 2016-03-02 23:27
ok here is the comparison:

``` bash
┌─[bubenkoff@Anatolys-MacBook-Pro-Work] - [~] - [2016-03-03 12:26:19]
└─[0] <> echo 'Select 1;' > select.sql; par_psql postgres --file=select.sql -a
┌─[bubenkoff@Anatolys-MacBook-Pro-Work] - [~] - [2016-03-03 12:26:24]
└─[0] <> echo 'Select 1;' > select.sql; psql postgres --file=select.sql -a
Select 1;
 ?column?
----------
        1
(1 row)
```

**Comment by gbb** [comment] 2016-03-02 23:34
Good, thank you.

Can you try this. Add 2 blank lines at the end. '\n\n' after the ; in your
echo command. You might need some parameters to echo , -e I think? To
interpret a newline.

Perhaps the parser may have a little bug relating to code that doesn't end
on a new line, or programs that are one line long. Let's test that.

Also, can you type 'cat select.sql' after you add the new line bit, to
check it's appearing correctly.

Finally, _please_ can you run the demonstration code listings from the
documentation, and tell me what happens. Copy it into a text file and run,
don't use echo. I know that demo code works great on Linux, so if the demo
code doesn't work on Mac, that could indicate a strange Mac bug.

**Comment by bubenkoff** [comment] 2016-03-02 23:37
nope, the same thing
i guess it's something after parsing
why DEBUG=1 doesn't add anything?

On 3 March 2016 at 00:34, Graeme B Bell notifications@github.com wrote:

> Good, thank you.
> 
> Can you try this. Add 2 blank lines at the end. '\n\n' after the ; in your
> echo command. You might need some parameters to echo , -e I think? To
> interpret a newline.
> 
> Perhaps the parser may have a little bug relating to code that doesn't end
> on a new line, or programs that are one line long. Let's test that.
> 
> Also, can you type 'cat select.sql' after you add the new line bit, to
> check it's appearing correctly.
> 
> Finally, _please_ can you run the demonstration code listings from the
> documentation, and tell me what happens. Copy it into a text file and run,
> don't use echo. I know that demo code works great on Linux, so if the demo
> code doesn't work on Mac, that could indicate a strange Mac bug.
> On 3 Mar 2016 12:27 am, "Anatoly Bubenkov" notifications@github.com
> wrote:
> 
> > ok here is the comparison:
> > 
> > ┌─[bubenkoff@Anatolys-MacBook-Pro-Work] - [~] - [2016-03-03 12:26:19]
> > └─[0] <> echo 'Select 1;' > select.sql; par_psql postgres
> > --file=select.sql -a
> > ┌─[bubenkoff@Anatolys-MacBook-Pro-Work] - [~] - [2016-03-03 12:26:24]
> > └─[0] <> echo 'Select 1;' > select.sql; psql postgres --file=select.sql
> > -a
> > Select 1;
> > 
> > ## ?column?
> > 
> > 1
> > (1 row)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/gbb/par_psql/issues/2#issuecomment-191491130.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gbb/par_psql/issues/2#issuecomment-191493683.

## 

Anatoly Bubenkov

**Comment by gbb** [comment] 2016-03-02 23:40
Hi,

Remember, I need you to follow all the steps I asked you to test or I won't
be able to help you with this further. Can you run the demo / documentation
example code now?

Graeme

**Comment by bubenkoff** [comment] 2016-03-02 23:44
./run_test.sh doesn't do anything, because it runs par_sql and it doesn't create db because it fails to execute any sql, as we already know...

**Comment by gbb** [comment] 2016-03-02 23:49
Ok, I was asking you to do it in order to double check your result in case
something else was happening. Perhaps some weird version of the echo
command in macos, for example.

I suspect it may be something like that. The BSD versions of some UNIX
commands can have slightly different parameters compared to Linux.
Occasionally slightly different behaviour. That could be enough to break
parpsql on mac.

I'll look at it next week when I'm back and see what the bug is. Thanks
very much for finding the bug and reporting it, and doing these tests with
me.

You're also very welcome to try to find the cause of the bug yourself. If
you find it and fix it and send it back here as a pull request I'll give
you credit for that in the documentation.

**Comment by bubenkoff** [comment] 2016-03-02 23:55
this is a great tool - thanks for it!
but i think it needs a full sql support to be accepted widely
because even on linux it's limited with the syntax
for example - redshift-specific queries as just wrongly parsed

**Comment by gbb** [comment] 2016-03-03 00:02
Thanks for the compliment!

However, there's now other alternatives already out there that allow
parallelization with a slightly broader range of SQL (see documentation),
so I think I won't be adding a bigger parser to ppsql. The scope of the
project is really limited to helping plain workflow-type sql take advantage
of parallelism in a minimalistic and backwards compatible way.

Or put differently, as it stands today, its 100% perfect for my own
projects and my colleagues projects, there's been nothing missing that we
need.

If someone else wants to extend/improve it for their own needs, they can
just press 'branch' and start working on it :-)

**Comment by gbb** [comment] 2016-03-24 05:10
So - 

There are two bugs, which affect macos/BSD but not linux. 
I've made a patch that fixes them, and hope to put it in place later today.
I just need to test the patch doesn't change the behaviour in linux. 

Thank you for notifying me about the faulty behaviour in macos.

**Comment by gbb** [comment] 2016-03-25 02:08
I've tested the fix, it seems to work nicely on my mac.
Please can you try it out Anatoly? @bubenkoff

**Comment by bubenkoff** [comment] 2016-03-25 09:12
works better now!
still not exactly as psql...

```
echo 'Select 1' > select.sql; psql postgres --file=select.sql -a
```

works

```
echo 'Select 1' > select.sql; par_psql postgres --file=select.sql -a
```

doesn't
but

```
echo 'Select 1;' > select.sql; psql postgres --file=select.sql -a
```

works

On 25 March 2016 at 03:08, Graeme B Bell notifications@github.com wrote:

> I've tested the fix, it seems to work nicely on my mac.
> Please can you try it out Anatoly? @bubenkoff
> https://github.com/bubenkoff
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/gbb/par_psql/issues/2#issuecomment-201108410

## 

Anatoly Bubenkov

**Comment by gbb** [comment] 2016-03-25 14:10
'Select 1' is not valid SQL, as I mentioned already.

It is not surprising that it didn't work.

Please can you stop putting invalid SQL into the program and expecting it
to run?

Instead, can you run the benchmarks and check that they complete for you?

./run_benchmarks.sh

**Comment by bubenkoff** [comment] 2016-03-25 14:22
look, im just comparing it to pure psql, what's wrong with that?

On 25 March 2016 at 15:10, Graeme B Bell notifications@github.com wrote:

> 'Select 1' is not valid SQL, as I mentioned already.
> 
> It is not surprising that it didn't work.
> 
> Please can you stop putting invalid SQL into the program and expecting it
> to run?
> 
> Instead, can you run the benchmarks and check that they complete for you?
> 
> ./run_benchmarks.sh
> On 25 Mar 2016 9:12 am, "Anatoly Bubenkov" notifications@github.com
> wrote:
> 
> > works better now!
> > still not exactly as psql...
> > 
> > ```
> > echo 'Select 1' > select.sql; psql postgres --file=select.sql -a
> > ```
> > 
> > works
> > 
> > ```
> > echo 'Select 1' > select.sql; par_psql postgres --file=select.sql -a
> > ```
> > 
> > doesn't
> > but
> > 
> > ```
> > echo 'Select 1;' > select.sql; psql postgres --file=select.sql -a
> > ```
> > 
> > works
> > 
> > On 25 March 2016 at 03:08, Graeme B Bell notifications@github.com
> > wrote:
> > 
> > > I've tested the fix, it seems to work nicely on my mac.
> > > Please can you try it out Anatoly? @bubenkoff
> > > https://github.com/bubenkoff
> > > 
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/gbb/par_psql/issues/2#issuecomment-201108410
> > 
> > ## 
> > 
> > Anatoly Bubenkov
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > https://github.com/gbb/par_psql/issues/2#issuecomment-201213914
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/gbb/par_psql/issues/2#issuecomment-201297473

## 

Anatoly Bubenkov

**Comment by gbb** [comment] 2016-03-25 14:41
Hi Anatoly,

If psql chooses to occasionally parse incorrect/bad statements that are not
actually SQL, that's up to those developers.

My software will not do this. You must give it valid SQL. If you give it
something which is not actually SQL, it won't run.

I have already told you clearly before that the program will not accept
broken/invalid SQL. So I have no idea at all why you're continuing to
discuss this.

That my SQL program only works with valid SQL is hardly surprising, and is
in keeping with the majority of software in the world.

I won't discuss this any further, I'm afraid. If you need a tool capable of
evaluating 'select 1' (no semi-colon), you will need to look elsewhere...
Perhaps you can write a parser yourself. That's the great thing about open
source.

Anyway, since your expectations here are completely unreasonable, and since
you won't accept that your clearly broken code is not actually SQL, and
since you repeatedly refuse to follow a simple, clear instruction to help
me check the software works correctly for you, I'm not willing to spend any
more time working with you on this.

Thanks for your original post noticing that the software didn't work on
MacOS. That is now fixed, the issue is now closed.

On 25 March 2016 at 15:10, Graeme B Bell notifications@github.com wrote:

> 'Select 1' is not valid SQL, as I mentioned already.
> 
> It is not surprising that it didn't work.
> 
> Please can you stop putting invalid SQL into the program and expecting it
> to run?
> 
> Instead, can you run the benchmarks and check that they complete for you?
> 
> ./run_benchmarks.sh
> On 25 Mar 2016 9:12 am, "Anatoly Bubenkov" notifications@github.com
> wrote:
> 
> > works better now!
> > still not exactly as psql...
> > 
> > ```
> > echo 'Select 1' > select.sql; psql postgres --file=select.sql -a
> > ```
> > 
> > works
> > 
> > ```
> > echo 'Select 1' > select.sql; par_psql postgres --file=select.sql -a
> > ```
> > 
> > doesn't
> > but
> > 
> > ```
> > echo 'Select 1;' > select.sql; psql postgres --file=select.sql -a
> > ```
> > 
> > works
> > 
> > On 25 March 2016 at 03:08, Graeme B Bell notifications@github.com
> > wrote:
> > 
> > > I've tested the fix, it seems to work nicely on my mac.
> > > Please can you try it out Anatoly? @bubenkoff
> > > https://github.com/bubenkoff
> > > 
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/gbb/par_psql/issues/2#issuecomment-201108410
> > 
> > ## 
> > 
> > Anatoly Bubenkov
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > https://github.com/gbb/par_psql/issues/2#issuecomment-201213914
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/gbb/par_psql/issues/2#issuecomment-201297473

## 

Anatoly Bubenkov

**Comment by bubenkoff** [comment] 2016-03-25 14:45
Hi Graeme B Bell,
if you don't trust me, try this tool:

_http://www.w3schools.com/sql/trysql.asp?filename=trysql_delete
http://www.w3schools.com/sql/trysql.asp?filename=trysql_delete_

_type:_

_select 1_

_and click RUN SQL_

_it will work, as it's VALID sql, just not having ; at the end!_
_and ; is a separator between the statements, and i have only one, so
what's wrong??_

On 25 March 2016 at 15:41, Graeme B Bell notifications@github.com wrote:

> Hi Anatoly,
> 
> If psql chooses to occasionally parse incorrect/bad statements that are not
> actually SQL, that's up to those developers.
> 
> My software will not do this. You must give it valid SQL. If you give it
> something which is not actually SQL, it won't run.
> 
> I have already told you clearly before that the program will not accept
> broken/invalid SQL. So I have no idea at all why you're continuing to
> discuss this.
> 
> That my SQL program only works with valid SQL is hardly surprising, and is
> in keeping with the majority of software in the world.
> 
> I won't discuss this any further, I'm afraid. If you need a tool capable of
> evaluating 'select 1' (no semi-colon), you will need to look elsewhere...
> Perhaps you can write a parser yourself. That's the great thing about open
> source.
> 
> Anyway, since your expectations here are completely unreasonable, and since
> you won't accept that your clearly broken code is not actually SQL, and
> since you repeatedly refuse to follow a simple, clear instruction to help
> me check the software works correctly for you, I'm not willing to spend any
> more time working with you on this.
> 
> Thanks for your original post noticing that the software didn't work on
> MacOS. That is now fixed, the issue is now closed.
> 
> look, im just comparing it to pure psql, what's wrong with that?
> 
> On 25 March 2016 at 15:10, Graeme B Bell notifications@github.com wrote:
> 
> > 'Select 1' is not valid SQL, as I mentioned already.
> > 
> > It is not surprising that it didn't work.
> > 
> > Please can you stop putting invalid SQL into the program and expecting it
> > to run?
> > 
> > Instead, can you run the benchmarks and check that they complete for you?
> > 
> > ./run_benchmarks.sh
> > On 25 Mar 2016 9:12 am, "Anatoly Bubenkov" notifications@github.com
> > wrote:
> > 
> > > works better now!
> > > still not exactly as psql...
> > > 
> > > ```
> > > echo 'Select 1' > select.sql; psql postgres --file=select.sql -a
> > > ```
> > > 
> > > works
> > > 
> > > ```
> > > echo 'Select 1' > select.sql; par_psql postgres --file=select.sql -a
> > > ```
> > > 
> > > doesn't
> > > but
> > > 
> > > ```
> > > echo 'Select 1;' > select.sql; psql postgres --file=select.sql -a
> > > ```
> > > 
> > > works
> > > 
> > > On 25 March 2016 at 03:08, Graeme B Bell notifications@github.com
> > > wrote:
> > > 
> > > > I've tested the fix, it seems to work nicely on my mac.
> > > > Please can you try it out Anatoly? @bubenkoff
> > > > https://github.com/bubenkoff
> > > > 
> > > > —
> > > > You are receiving this because you were mentioned.
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/gbb/par_psql/issues/2#issuecomment-201108410
> > > 
> > > ## 
> > > 
> > > Anatoly Bubenkov
> > > 
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/gbb/par_psql/issues/2#issuecomment-201213914
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > https://github.com/gbb/par_psql/issues/2#issuecomment-201297473
> 
> ## 
> 
> Anatoly Bubenkov
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/gbb/par_psql/issues/2#issuecomment-201306829
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/gbb/par_psql/issues/2#issuecomment-201317455

## 

Anatoly Bubenkov

**Comment by gbb** [comment] 2016-03-26 01:13
- It is not an issue of trust. This is an issue of fact (see below). You are simply mistaken about what is or isn't SQL, and I am not interested in discussing that further. From the docs: http://www.postgresql.org/docs/current/static/plpgsql-structure.html
  "Each declaration and **each statement within a block** is terminated by a semicolon."
- If you believe the general, ordinary behaviour of psql is to parse statements without a semicolon, then open psql, type 'select 1', press return, and wait for the result. You will be waiting for some time. I understand that by a peculiar quirk, psql appears to add a semicolon automatically onto that one-statement query passed in by pipe. (But only when there is **one statement** - try echo 'select 1 select 2' | psql; it will not work). By definition, a one-statement query is not suitable for parallelisation here, and thus, it is totally irrelevant to a parallelising SQL parser. Furthermore, I have no interest in implementing peculiar psql quirks. 
- I am sorry but I am not interested in helping you any further with this. I have made my position clear twice. You must accept this: Anything you want to have, which I do not wish to provide, you must make for yourself. That is life.
- I am closing the issue as the MacOS bug has now been solved, and I will not welcome further discussion on the topics of this Issue here or elsewhere. 
- I'd suggest you start your own project to implement this quirk/feature if you care about it.

**Closed as completed by gbb** 2016-03-26 01:13 UTC
